### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1154]
Plan:
- [x] Run CheckStyle
   - [ ] run only: when `*.java`, `*.properties`, `pom.xml`, `src/main/config/checkstyle.xml` or `src/main/config/checkstyle-suppressions.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run PMD
   - [ ] run only: when `*.java`, `pom.xml`, `src/main/config/pmd.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Check license header
   - [ ] run only: when `*.java`, `*.groovy`, `src/main/config/license_header.txt`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Check `pom.xml`
   - [ ] run only: when `pom.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run bootlint
   - [ ] run only: when `src/main/**/*.html`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run rflint
   - [ ] run only: when `src/test/robotframework/**/*.robot`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run shellcheck
   - [ ] check also: `infra/vagrant/provisioning/roles/mystamps-backup/templates/remote-backup.sh`
   - [ ] run only: when `.github/workflows/static-analysis.yml`, `src/main/scripts/**/*.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run jest
   - [ ] check also: `src/main/frontend/package.json` and `src/main/frontend/package-lock.json`
   - [ ] try to cache: `Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.gz to /home/runner/.m2/repository/com/github/eirslett/node/10.16.0/node-10.16.0-linux-x64.tar.gz`
   - [ ] run only: when `*.js`, `pom.xml`, `.github/workflows/unit-tests.yml` files were modified
   - [ ] run always: on `prod` branch
- [x] Run html5validator
   - [ ]  check also: `src/main/config/nginx/503.*html` (#760)
   - [ ] run only: when `src/main/webapp/WEB-INF/views/**/*.html`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run enforcer maven plugin
   - [ ] run only: when `pom.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run unit tests
   - [ ] run only: when `*.java`, `*.groovy`, `pom.xml`, `.github/workflows/unit-tests.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run CodeNarc
   - [ ] run only: when `*.groovy`, `pom.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run SpotBugs
   - [ ] run only: when `*.java`, `pom.xml`, `src/main/config/spotbugs-filter.xml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run ansible-lint
   - [ ] run only: when `src/main/scripts/ci/ansible/deploy.yml`, `infra/vagrant/provisioning/**/*.yml`, `.github/workflows/static-analysis.yml`, `src/main/scripts/execute-command.sh` files were modified
   - [ ] run always: on `prod` branch
- [x] Run integration tests
   - [x] on H2
   - [x] on MySQL
   - [x] on PostgreSQL
      - [ ] add a healthcheck (`pg_isready`)
- [x] ~~Run Danger (only for PRs)~~ (no needed: #1600)
- [x] deploy on production server
   - [x] depends on successful execution of other pipelines (unit and integration tests, static analysis) (will be solved in #1619)
   - [x] `export UPTIMEROBOT_APIKEY=`
- [ ] remove `gh1154_github_actions` branch
- [x] remove `.travis.yml`
- [x] update `NEWS.txt`
- [x] update a badge (example: https://github.com/nackjicholson/aiosql)
- [x] decide on "travis" profile
- [x] update other places (`git grep -i travis`)
- [ ] maven: filter out `Downloading` messages
- [x] think about how to save robot framework reports in case of failure
- [ ] revise Travis-related issues:
   - [x] #201 
   - [ ] #373
   - [x] #516
   - [x] #564
   - [x] #607
   - [x] #632
   - [x] #1085
   - [x] #1141
   - [ ] #1165
   - [ ] #1467
   - [ ] #1479
- [ ] implement diagram generation in `generated-assets` branch
- [x] ensure that pipelines are running for PRs (`on: [ push, pull_request ]`)
- [x] save (see `actions/upload-artifact`) robot framework result as an artifact (in case of failure: `if: ${{ failure() }}`)
- [ ] try to cache `~/.m2` folder with all dependencies
- [x] for `master` branch only (`pom.xml`, `<script>.sh`): generate a list of differences in versions between us and Spring Boot
- [ ] publish code coverage to a separate branch (github pages?)
- [ ] `export MAVEN_OPTS='-Xss256k'`
- [x] Travis: remove a webhook and app
- [x] Travis: remove `VAULT_PASSWORD` (https://app.travis-ci.com/github/php-coder/mystamps/settings)

See:
- [ ] https://help.github.com/en/actions
- [ ] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
- [ ] https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
- [x] https://github.com/actions/checkout
- [x] https://github.com/actions/setup-java
- [x] https://github.com/actions/upload-artifact
   - [ ] https://github.com/actions/toolkit/tree/main/packages/artifact
- [ ] https://github.com/actions/cache
- [ ] https://github.com/marketplace/actions/hashicorp-setup-terraform
- [ ] https://docs.github.com/en/free-pro-team@latest/actions/guides
- [ ] https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven
- [ ] https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
- [x] https://docs.github.com/en/actions/using-containerized-services/about-service-containers
- [x] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices
- [x] https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
- [ ] https://lab.github.com/githubtraining/github-actions:-writing-javascript-actions
- [x] https://rieckpil.de/github-actions-for-java-automate-your-maven-workflows/ (+pinboard)
- [x] https://epsi-rns.gitlab.io/devops/2020/02/18/ci-cd-github-workflows/ (+pinboard)
- [ ] https://www.edwardthomson.com/blog/github_actions_advent_calendar.html
- [ ] https://blog.frankel.ch/github-actions-maven-releases/
- [x] https://medium.com/@cakeinpanic/github-actions-база-2501445e7392 :ru:
- [ ] https://medium.com/@cakeinpanic/github-actions-пишем-свой-8eb0a05c3e8a :ru:
- [ ] https://github.blog/2021-03-04-4-things-you-didnt-know-you-could-do-with-github-actions/ (+pinboard)
- [ ] https://blog.codecentric.de/en/2021/02/github-actions-pipeline/ (+pinboard)
- [ ] https://blog.codecentric.de/en/2021/03/github-container-registry/ (+pinboard)
- [ ] https://blog.codecentric.de/en/2021/03/github-actions-nextgen-cicd/ (+pinboard)
- [ ] https://www.actionsbyexample.com
- [x] https://towardsdatascience.com/github-actions-everything-you-need-to-know-to-get-started-537f1dffa0ed (https://gist.github.com/ahmedbesbes/34fefc4ff71ce33ff16fe0acf0a3c5d2#file-workflow-yaml)
- [ ] https://fastpages.fast.ai/actions/markdown/2020/03/06/fastpages-actions.html
- [ ] https://blog.gitguardian.com/github-actions-security-cheat-sheet/ (+pinboard)
- [ ] https://levelup.gitconnected.com/github-actions-how-to-share-data-between-jobs-fc1547defc3e (+pinboard)

**Comment by php-coder** [comment]
Video: https://youtu.be/QoCSvwkP_lQ 🇷🇺

**Comment by php-coder** [comment]
Travis CI has stopped to work: `Builds have been temporarily disabled for public repositories due to a negative credit balance.` I had 10000 credits and they have been used. Also I can't use OSS credits: `You have used 0 of your 0 monthly credits`

**Comment by php-coder** [comment]
> Also I can't use OSS credits: You have used 0 of your 0 monthly credits

I have contacted with support and got 25k credits. Travis is working now.
