### ISSUE TITLE
Automatically convert todo comments in code to the issues

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1610]
Follow-up to: #1595

Currently I'm investigating the idea to supply a similar automation by myself:
- when code gets submitted to `master` branch, github action is spinned up:
  - it clones a repository
  - runs pdd
  - collects all todos
  - commits (with information about an original commit) the results (`pdd.xml` + `todos-in-code.tsv`) into a separate branch named `generated-todos`; no commit if there were no new todos discovered
  - it also creates the issues for new todos. To link a puzzle with related issue, the `todos-on-github.tsv` is used. That file is also committed to the `generated-todos` branch
- IDEA: close an issue when a puzzle gets removed (_resolution_: extracted to #1616)
- IDEA: remove a link when an issue gets closed manually (_resolution_: extracted to #1617)
- IDEA: consider import of https://www.0pdd.com/xml?name=php-coder/mystamps (with closed puzzles) (_resolution: it doen't worth it_)

Checklist:
- [x] Generate `pdd.xml`
- [x] Generate `todos-in-code.tsv`
- [x] Generate a mapping between puzzles ids and existing issues
- [x] Deal with incorrect comments (with trailing `-->` or `*/`)
- [x] Create new issues for todos without mapping
- Cleanup
   - [x] remove `gh1595_extract_todos` branch
   - [x] remove `generated-todos-test` branch
- Document
   - [x] put a workaround for pdd/wiremock back
   - [x] create `pdd-xml-to-json.sh` as pdd doesn't support JSON output (+pdd issue)
   - [x] modify comments to avoid having next lines in a title
   - [x] workaround: 2 search queries because github doesn't support OR
   - [x] workaround: possible collisions because GitHub doesn't support exatch match
   - [x] pdd: workaround for trailing `-->` (pdd gh111)

**Comment by php-coder** [comment]
Done!
