### ISSUE TITLE
Decommission of static analyzers

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1669]
- [x] CheckStyle
   - [x] remove `CheckStyle: ignore` and `@SuppressWarnings("checkstyle:*")` comments
   - [x] #260
   - [x] #1015
- [x] PMD
   - [x] remove `@SuppressWarnings("PMD.*")` comments
   - [x] #195
   - [x] #261
   - [x] #1018
   - [x] #1250
   - [x] #1646
- [x] sortpom
   - [x] #1174
- [x] boolint
   - [x] #316
- [x] rflint
   - [x] #1104 need to decide what to do
- [x] shellcheck
   - [x] remove `shellcheck disable` comments
   - [x] #1615
   - [x] #710
- [x] html5validator
   - [x] #541
   - [x] #760
- [x] ansible-lint
   - [x] #1144
   - [x] #1515
   - [x]  #1570
- [x] CodeNarc
   - [x] remove `@SuppressWarnings` from Groovy code
   - [x] #508
   - [x] #539
   - [x] #994
   - [x] #1187
- [x] SpotBugs
   - [x] #480
   - [x] #1190
   - [x] #1198
   - [x] #1258
   - [x] #184
   - [x] #185
- [x] ErrorProne
   - [x] #999
   - [x] #1069
   - [x] #1235
   - [x] #1440
   - [x] will help to resolve #1350
- [ ] update decisions log: mention removal of error-prone and added workaround (see bb4afedd7b90f015fec4b951be13c0679690875a)
- [x] no need to add other static analyzers
   - [x] #183
   - [x] #422 looks useful, let's keep it
   - [x] #585
   - [x] #613
   - [x] #614
   - [x] #799
   - [x] #1062 looks useful, let's keep it
   - [x] #1201
   - [x] #1202
   - [x] #1203
   - [x] #1212 looks useful, let's keep it
   - [x] #1109 looks useful, let's keep it
- [x] #574 will have a lesser scope

`maven-enforcer-plugin`, probably, can stay altogether with `maven-license-plugin`.
